export interface Doctor {
  id: string;
  name: string;
  specialty: string;
  qualification: string;
  experience: number;
  rating: number;
  reviews: number;
  patients: number;
  availableToday: boolean;
  timeRange: string;
  image: string;
  about: string;
  services: string[];
}

export interface TimeSlot {
  time: string;
  period: 'morning' | 'afternoon' | 'evening';
  available: boolean;
}

export interface ChatMessage {
  id: string;
  sender: 'doctor' | 'patient';
  message: string;
  time: string;
}

export const doctors: Doctor[] = [
  {
    id: "1",
    name: "Dr. Prakash Das",
    specialty: "Cardiologist",
    qualification: "MBBS, MD",
    experience: 12,
    rating: 4.8,
    reviews: 342,
    patients: 1500,
    availableToday: true,
    timeRange: "10:00 AM - 4:00 PM",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face",
    about: "Experienced cardiologist specializing in interventional cardiology and heart disease prevention.",
    services: ["Heart Checkup", "ECG", "Echocardiography", "Stress Test", "Cardiac Consultation"],
  },
  {
    id: "2",
    name: "Dr. Anita Sharma",
    specialty: "Dermatologist",
    qualification: "MBBS, MD, DNB",
    experience: 8,
    rating: 4.9,
    reviews: 215,
    patients: 980,
    availableToday: true,
    timeRange: "9:00 AM - 1:00 PM",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    about: "Expert in cosmetic dermatology and advanced skin treatments.",
    services: ["Skin Consultation", "Acne Treatment", "Laser Therapy", "Hair Treatment", "Cosmetic Procedures"],
  },
  {
    id: "3",
    name: "Dr. Rajesh Kumar",
    specialty: "Orthopedic",
    qualification: "MBBS, MS",
    experience: 15,
    rating: 4.7,
    reviews: 428,
    patients: 2100,
    availableToday: false,
    timeRange: "11:00 AM - 5:00 PM",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face",
    about: "Specialist in joint replacement and sports injury management.",
    services: ["Joint Replacement", "Fracture Treatment", "Sports Injury", "Spine Surgery", "Physiotherapy"],
  },
  {
    id: "4",
    name: "Dr. Meera Patel",
    specialty: "Pediatrician",
    qualification: "MBBS, DCH",
    experience: 10,
    rating: 4.9,
    reviews: 567,
    patients: 3200,
    availableToday: true,
    timeRange: "8:00 AM - 2:00 PM",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964f8c0?w=400&h=400&fit=crop&crop=face",
    about: "Compassionate pediatrician focused on child health and wellness.",
    services: ["Well-child Visits", "Vaccination", "Growth Monitoring", "Nutrition Counseling"],
  },

  {
    id: "5",
    name: "Dr. Arjun Reddy",
    specialty: "Neurologist",
    qualification: "MBBS, DM",
    experience: 14,
    rating: 4.8,
    reviews: 389,
    patients: 1800,
    availableToday: true,
    timeRange: "12:00 PM - 6:00 PM",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face",
    about: "Neurology expert treating stroke, epilepsy, and migraines.",
    services: ["Brain Scan", "Stroke Care", "Epilepsy Treatment", "Migraine Management"],
  },
  {
    id: "6",
    name: "Dr. Kavita Rao",
    specialty: "Gynecologist",
    qualification: "MBBS, MD",
    experience: 11,
    rating: 4.9,
    reviews: 512,
    patients: 2400,
    availableToday: true,
    timeRange: "9:30 AM - 3:30 PM",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face",
    about: "Specialist in women's health and high-risk pregnancies.",
    services: ["Pregnancy Care", "Infertility Treatment", "PCOS Treatment", "Women Health Checkup"],
  },
  {
    id: "7",
    name: "Dr. Rohit Sen",
    specialty: "ENT Specialist",
    qualification: "MBBS, MS",
    experience: 9,
    rating: 4.6,
    reviews: 198,
    patients: 870,
    availableToday: false,
    timeRange: "2:00 PM - 7:00 PM",
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&h=400&fit=crop&crop=face",
    about: "Treats ear, nose and throat disorders with advanced techniques.",
    services: ["Hearing Test", "Sinus Treatment", "Tonsil Surgery"],
  },
  {
    id: "8",
    name: "Dr. Neha Verma",
    specialty: "Psychiatrist",
    qualification: "MBBS, MD",
    experience: 13,
    rating: 4.8,
    reviews: 301,
    patients: 1400,
    availableToday: true,
    timeRange: "10:00 AM - 4:00 PM",
    image: "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=400&h=400&fit=crop&crop=face",
    about: "Expert in mental health, anxiety, and depression management.",
    services: ["Depression Therapy", "Anxiety Treatment", "Counseling"],
  },
  {
    id: "9",
    name: "Dr. Sameer Ali",
    specialty: "General Physician",
    qualification: "MBBS",
    experience: 7,
    rating: 4.5,
    reviews: 154,
    patients: 650,
    availableToday: true,
    timeRange: "8:00 AM - 12:00 PM",
    image: "https://images.unsplash.com/photo-1612277795421-9bc7706a4a34?w=400&h=400&fit=crop&crop=face",
    about: "Primary healthcare expert for all general medical conditions.",
    services: ["General Checkup", "Fever Treatment", "Blood Test"],
  },
  {
    id: "10",
    name: "Dr. Priya Menon",
    specialty: "Ophthalmologist",
    qualification: "MBBS, MS",
    experience: 16,
    rating: 4.9,
    reviews: 610,
    patients: 3500,
    availableToday: true,
    timeRange: "11:00 AM - 5:00 PM",
    image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=400&h=400&fit=crop&crop=face",
    about: "Eye specialist with expertise in cataract and LASIK surgery.",
    services: ["Eye Checkup", "Cataract Surgery", "LASIK", "Vision Test"],
  },

  /* 11 - 20 */

  {
    id: "11",
    name: "Dr. Vikram Joshi",
    specialty: "Urologist",
    qualification: "MBBS, MCh",
    experience: 12,
    rating: 4.7,
    reviews: 267,
    patients: 1100,
    availableToday: false,
    timeRange: "1:00 PM - 6:00 PM",
    image: "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&h=400&fit=crop&crop=face",
    about: "Specialist in kidney stones and urinary disorders.",
    services: ["Kidney Stone Treatment", "Prostate Care", "Urinary Infection"],
  },
  {
    id: "12",
    name: "Dr. Sneha Iyer",
    specialty: "Endocrinologist",
    qualification: "MBBS, DM",
    experience: 10,
    rating: 4.8,
    reviews: 245,
    patients: 1300,
    availableToday: true,
    timeRange: "10:30 AM - 3:30 PM",
    image: "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=400&h=400&fit=crop&crop=face",
    about: "Expert in diabetes and thyroid management.",
    services: ["Diabetes Care", "Thyroid Treatment", "Hormonal Therapy"],
  },
  {
    id: "13",
    name: "Dr. Karan Malhotra",
    specialty: "Pulmonologist",
    qualification: "MBBS, MD",
    experience: 9,
    rating: 4.6,
    reviews: 187,
    patients: 900,
    availableToday: true,
    timeRange: "9:00 AM - 2:00 PM",
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&h=400&fit=crop&crop=face",
    about: "Respiratory disease specialist treating asthma and COPD.",
    services: ["Asthma Care", "Lung Function Test", "Sleep Study"],
  },
  {
    id: "14",
    name: "Dr. Ritu Khanna",
    specialty: "Dentist",
    qualification: "BDS, MDS",
    experience: 6,
    rating: 4.7,
    reviews: 199,
    patients: 760,
    availableToday: true,
    timeRange: "8:00 AM - 1:00 PM",
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop&crop=face",
    about: "Cosmetic dentist specializing in smile design.",
    services: ["Teeth Cleaning", "Root Canal", "Braces", "Dental Implants"],
  },
  {
    id: "15",
    name: "Dr. Manish Gupta",
    specialty: "Oncologist",
    qualification: "MBBS, DM",
    experience: 18,
    rating: 4.9,
    reviews: 722,
    patients: 4000,
    availableToday: false,
    timeRange: "12:00 PM - 6:00 PM",
    image: "https://images.unsplash.com/photo-1580281657521-47c4eaf5bde0?w=400&h=400&fit=crop&crop=face",
    about: "Cancer specialist with expertise in chemotherapy and radiation therapy.",
    services: ["Cancer Screening", "Chemotherapy", "Radiation Therapy"],
  },
  {
    id: "16",
    name: "Dr. Alok Singh",
    specialty: "Gastroenterologist",
    qualification: "MBBS, MD",
    experience: 11,
    rating: 4.7,
    reviews: 284,
    patients: 1200,
    availableToday: true,
    timeRange: "10:00 AM - 4:00 PM",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    about: "Digestive system specialist for liver and stomach diseases.",
    services: ["Endoscopy", "Liver Treatment", "Acidity Treatment"],
  },
  {
    id: "17",
    name: "Dr. Pooja Nair",
    specialty: "Rheumatologist",
    qualification: "MBBS, MD",
    experience: 13,
    rating: 4.8,
    reviews: 312,
    patients: 1400,
    availableToday: true,
    timeRange: "9:00 AM - 2:00 PM",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964f8c0?w=400&h=400&fit=crop&crop=face",
    about: "Specialist in arthritis and autoimmune disorders.",
    services: ["Arthritis Treatment", "Joint Pain Care", "Autoimmune Therapy"],
  },
  {
    id: "18",
    name: "Dr. Sunil Mehta",
    specialty: "Nephrologist",
    qualification: "MBBS, DM",
    experience: 17,
    rating: 4.9,
    reviews: 488,
    patients: 2600,
    availableToday: false,
    timeRange: "1:00 PM - 6:00 PM",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face",
    about: "Kidney specialist with expertise in dialysis care.",
    services: ["Kidney Function Test", "Dialysis", "Hypertension Management"],
  },
  {
    id: "19",
    name: "Dr. Aisha Khan",
    specialty: "Nutritionist",
    qualification: "MBBS, MSc Nutrition",
    experience: 7,
    rating: 4.6,
    reviews: 173,
    patients: 800,
    availableToday: true,
    timeRange: "8:00 AM - 12:00 PM",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face",
    about: "Expert in diet planning and weight management.",
    services: ["Diet Planning", "Weight Loss Program", "PCOS Diet"],
  },
  {
    id: "20",
    name: "Dr. Harish Chandra",
    specialty: "Plastic Surgeon",
    qualification: "MBBS, MCh",
    experience: 14,
    rating: 4.8,
    reviews: 354,
    patients: 1700,
    availableToday: true,
    timeRange: "11:00 AM - 4:00 PM",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face",
    about: "Specialist in reconstructive and cosmetic surgery.",
    services: ["Cosmetic Surgery", "Scar Removal", "Reconstructive Surgery"],
  },
];

export const timeSlots: TimeSlot[] = [
  { time: "9:00 AM", period: "morning", available: true },
  { time: "9:30 AM", period: "morning", available: true },
  { time: "10:00 AM", period: "morning", available: false },
  { time: "10:30 AM", period: "morning", available: true },
  { time: "11:00 AM", period: "morning", available: true },
  { time: "11:30 AM", period: "morning", available: false },
  { time: "2:00 PM", period: "afternoon", available: true },
  { time: "2:30 PM", period: "afternoon", available: true },
  { time: "3:00 PM", period: "afternoon", available: false },
  { time: "3:30 PM", period: "afternoon", available: true },
  { time: "5:00 PM", period: "evening", available: true },
  { time: "5:30 PM", period: "evening", available: true },
  { time: "6:00 PM", period: "evening", available: true },
  { time: "6:30 PM", period: "evening", available: false },
];

export const chatMessages: ChatMessage[] = [
  { id: "1", sender: "doctor", message: "Hi, I'm sorry to hear that you're not feeling well. Can you tell me more about your symptoms?", time: "10:00 AM" },
  { id: "2", sender: "patient", message: "I've been having stomach pain and nausea for the past two days.", time: "10:02 AM" },
  { id: "3", sender: "doctor", message: "I understand. Here are some things you can try:", time: "10:05 AM" },
  { id: "4", sender: "doctor", message: "Place a warm compress on your stomach area to help ease the discomfort.", time: "10:05 AM" },
  { id: "5", sender: "doctor", message: "Try over-the-counter antacids for relief.", time: "10:06 AM" },
  { id: "6", sender: "doctor", message: "Eat bland foods like rice, toast, and bananas.", time: "10:06 AM" },
  { id: "7", sender: "doctor", message: "Drink lots of water to stay hydrated.", time: "10:07 AM" },
  { id: "8", sender: "patient", message: "Thank you doctor, I'll try these. Should I come for a visit if it doesn't improve?", time: "10:10 AM" },
  { id: "9", sender: "doctor", message: "Yes, if symptoms persist for more than 3 days, please book an appointment. Take care!", time: "10:12 AM" },
];